export {default as Features} from './features/Features';
export {default as Footer} from './footer/Footer';
export {default as GlobalNetwork} from './globalnetwork/GlobalNetwork';
export {default as Testimonials} from './testimonials/Testimonials';
export {default as Header} from './header/Header';
export {default as Info} from './info/Info';
export {default as Navbar} from './navbar/Navbar';
export {default as Plans} from './plans/Plans';
export {default as Subscribe} from './subscribe/Subscribe';